services:
  activity:
    image: jdrouet/docker-activity:canary
    privileged: true
    build: ..
    # command: file --format json /data/output.jsonp
    command: tcp-socket --format json vector:9000
    networks:
      - backend
    volumes:
      - /sys/class/powercap:/sys/class/powercap:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - storage:/data
    depends_on:
      - vector

  vector:
    image: timberio/vector:latest-alpine
    networks:
      - backend
    ports:
      - "9091:9090" # for Prometheus
      - "9000:9000" # for docker-activity input
      - "9001:9001" # for Vector API (optional)
    volumes:
      - ./vector.toml:/etc/vector/vector.toml:ro
      - storage:/data:ro
    entrypoint: ["/usr/local/bin/vector"]
    command: ["--config", "/etc/vector/vector.toml"]
networks:
  backend: {}

volumes:
  storage: {}
