[package]
name = "docker-activity"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bollard = { version = "^0.11" }
clap = { version = "3.0.0-beta.5" }
futures = { version = "0.3.17" }
futures-util = { version = "0.3.17" }
powercap = { version = "0.3.2" }
tokio = { version = "1.13.0", features = ["full"] }
